### ISSUE TITLE
incompatible with IDEA 2019.3 EAP

### ISSUE THREAD

**Issue by BorzdeG** [JetBrains/idea-gitignore#603]
`.ignore not loaded: until build 193.0 < IU-193.2956.37`

**Comment by Scott-G** [comment]
Same issue here.

**Comment by nowm** [comment]
Try to uninstall and install it again. I had installed it in PhpStorm, and it stopped work in 2019.2. I saw a strange version string in the plugin: "3.1.xxx -> 3.2.2.192" (I cannot remember which numbers were in place of "xxx", but I'm sure major.minor were 3.1). It was literary old_version + right_arrow + new_version.

After uninstalling it and installing it again, it started to show the "3.2.2.192" version and incompatibility message was disappeared.

**Comment by BorzdeG** [comment]
@nowm I am using the latest version:
<img width="358" alt="image" src="https://user-images.githubusercontent.com/2332528/64919119-d6880d80-d7af-11e9-8114-03db7fada03d.png">

**Comment by studio-salamander** [comment]
Same issue

**Comment by BrianGilbert** [comment]
@BorzdeG how can I make use of this fix straight away?

**Comment by BorzdeG** [comment]
```
com.intellij.ide.plugins.StartupAbortedException: Fatal error initializing plugin mobi.hsz.idea.gitignore
	at com.intellij.ide.plugins.PluginManager.handleComponentError(PluginManager.java:55)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.handleInitComponentError(PlatformComponentManagerImpl.kt:247)
	at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:50)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:100)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:72)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:65)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.createComponents(PlatformComponentManagerImpl.kt:177)
	at com.intellij.openapi.project.impl.DefaultProject$1$1.init(DefaultProject.java:71)
	at com.intellij.openapi.project.impl.DefaultProject$1.init(DefaultProject.java:95)
	at com.intellij.openapi.project.impl.DefaultProjectTimed.get(DefaultProjectTimed.java:35)
	at com.intellij.openapi.project.impl.DefaultProject.getDelegate(DefaultProject.java:122)
	at com.intellij.openapi.project.impl.DefaultProject.getMessageBus(DefaultProject.java:238)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.getDefaultProject(ProjectManagerImpl.java:370)
	at com.intellij.openapi.wm.impl.welcomeScreen.FlatWelcomeFrame.getProject(FlatWelcomeFrame.java:875)
	at com.intellij.openapi.wm.IdeFocusManager.findByComponent(IdeFocusManager.java:179)
	at com.intellij.openapi.wm.IdeFocusManager.findInstanceByComponent(IdeFocusManager.java:171)
	at com.intellij.ui.popup.AbstractPopup.getFocusManager(AbstractPopup.java:1265)
	at com.intellij.ui.popup.AbstractPopup.dispose(AbstractPopup.java:1430)
	at com.intellij.ui.popup.WizardPopup.dispose(WizardPopup.java:151)
	at com.intellij.ui.popup.list.ListPopupImpl.dispose(ListPopupImpl.java:326)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.dispose(PopupFactoryImpl.java:276)
	at com.intellij.openapi.util.ObjectTree$1.execute(ObjectTree.java:27)
	at com.intellij.openapi.util.ObjectTree$1.execute(ObjectTree.java:23)
	at com.intellij.openapi.util.ObjectNode$1.execute(ObjectNode.java:103)
	at com.intellij.openapi.util.ObjectNode$1.execute(ObjectNode.java:71)
	at com.intellij.openapi.util.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:198)
	at com.intellij.openapi.util.ObjectNode.execute(ObjectNode.java:71)
	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:146)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:116)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:112)
	at com.intellij.ui.popup.WizardPopup.disposeAllParents(WizardPopup.java:252)
	at com.intellij.ui.popup.list.ListPopupImpl.handleNextStep(ListPopupImpl.java:461)
	at com.intellij.ui.popup.list.ListPopupImpl._handleSelect(ListPopupImpl.java:415)
	at com.intellij.ui.popup.list.ListPopupImpl.handleSelect(ListPopupImpl.java:361)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.handleSelect(PopupFactoryImpl.java:296)
	at com.intellij.ui.popup.list.ListPopupImpl$MyMouseListener.mouseReleased(ListPopupImpl.java:526)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at com.intellij.ui.popup.list.ListPopupImpl$MyList.processMouseEvent(ListPopupImpl.java:583)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:844)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:776)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:705)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:421)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.intellij.diagnostic.PluginException: Cannot create class com.intellij.openapi.vcs.impl.VcsFileStatusProvider [Plugin: mobi.hsz.idea.gitignore]
	... 75 more
Caused by: com.intellij.diagnostic.PluginException: Cannot create class com.intellij.openapi.vcs.impl.VcsFileStatusProvider
	at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:382)
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:12)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:58)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.instantiateClass(PlatformComponentManagerImpl.kt:491)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.createLightService(PlatformComponentManagerImpl.kt:434)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.getOrCreateLightService(PlatformComponentManagerImpl.kt:345)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.getLightService$intellij_platform_serviceContainer(PlatformComponentManagerImpl.kt:317)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.getService(PlatformComponentManagerImpl.kt:282)
	at com.intellij.openapi.project.impl.DefaultProject.getService(DefaultProject.java:215)
	at com.intellij.openapi.components.ComponentManager.getService(ComponentManager.java:114)
	at com.intellij.openapi.vcs.impl.VcsFileStatusProvider.getInstance(VcsFileStatusProvider.java:35)
	at com.intellij.openapi.vcs.impl.FileStatusManagerImpl.<init>(FileStatusManagerImpl.java:86)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:44)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.instantiateClassWithConstructorInjection(PlatformComponentManagerImpl.kt:500)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:52)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:39)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:100)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:72)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:65)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.getService(PlatformComponentManagerImpl.kt:288)
	at com.intellij.openapi.project.impl.DefaultProject.getService(DefaultProject.java:215)
	at com.intellij.openapi.components.ComponentManager.getService(ComponentManager.java:114)
	at com.intellij.openapi.vcs.FileStatusManager.getInstance(FileStatusManager.java:17)
	at mobi.hsz.idea.gitignore.IgnoreManager.<init>(IgnoreManager.java:297)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:44)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.instantiateClassWithConstructorInjection(PlatformComponentManagerImpl.kt:500)
	at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:35)
	... 72 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.instantiateClass(PlatformComponentManagerImpl.kt:473)
	... 103 more
Caused by: java.lang.IllegalStateException: @NotNull method com/intellij/openapi/vcs/changes/ChangeListManager.getInstance must not return null
	at com.intellij.openapi.vcs.changes.ChangeListManager.$$$reportNull$$$0(ChangeListManager.java)
	at com.intellij.openapi.vcs.changes.ChangeListManager.getInstance(ChangeListManager.java:24)
	at com.intellij.openapi.vcs.impl.VcsFileStatusProvider.<init>(VcsFileStatusProvider.java:42)
	... 108 more
```

```
Typeahead request blocked

com.intellij.openapi.wm.impl.FocusManagerImpl$1: Time: 4193; cause: Abstract Popup Disposal; runnable waiting for the focus change: 
	at com.intellij.openapi.wm.impl.FocusManagerImpl.typeAheadUntil(FocusManagerImpl.java:211)
	at com.intellij.ui.popup.AbstractPopup.dispose(AbstractPopup.java:1425)
	at com.intellij.ui.popup.WizardPopup.dispose(WizardPopup.java:151)
	at com.intellij.ui.popup.list.ListPopupImpl.dispose(ListPopupImpl.java:326)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.dispose(PopupFactoryImpl.java:276)
	at com.intellij.openapi.util.ObjectTree$1.execute(ObjectTree.java:27)
	at com.intellij.openapi.util.ObjectTree$1.execute(ObjectTree.java:23)
	at com.intellij.openapi.util.ObjectNode$1.execute(ObjectNode.java:103)
	at com.intellij.openapi.util.ObjectNode$1.execute(ObjectNode.java:71)
	at com.intellij.openapi.util.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:198)
	at com.intellij.openapi.util.ObjectNode.execute(ObjectNode.java:71)
	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:146)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:116)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:112)
	at com.intellij.ui.popup.WizardPopup.disposeAllParents(WizardPopup.java:252)
	at com.intellij.ui.popup.list.ListPopupImpl.handleNextStep(ListPopupImpl.java:461)
	at com.intellij.ui.popup.list.ListPopupImpl._handleSelect(ListPopupImpl.java:415)
	at com.intellij.ui.popup.list.ListPopupImpl.handleSelect(ListPopupImpl.java:361)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.handleSelect(PopupFactoryImpl.java:296)
	at com.intellij.ui.popup.list.ListPopupImpl$MyMouseListener.mouseReleased(ListPopupImpl.java:526)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at com.intellij.ui.popup.list.ListPopupImpl$MyList.processMouseEvent(ListPopupImpl.java:583)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:844)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:776)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:705)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:421)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by BorzdeG** [comment]
> @BorzdeG how can I make use of this fix straight away?

Build and install the plugin locally.

build: `./gradlew assemble`
install: https://www.jetbrains.com/help/idea/managing-plugins.html#install_plugin_from_disk

**Comment by lunetics** [comment]
WIth gradle manual build i get following error message:
```
> Task :compileJava FAILED
/tmp/idea-gitignore/src/mobi/hsz/idea/gitignore/indexing/IgnoreSearchScope.java:86: error: method does not override or implement a method from a supertype
    @Override
    ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
```
Thought, I updated to latest EAP today:
Build #PS-193.4099.12, built on October 2, 2019

**Comment by BorzdeG** [comment]
https://github.com/JetBrains/intellij-community/commit/97f24499a96f9ae718a3b9973a498777bda365d1

Somewhere flashed documentation, how to support multiple IDE versions of the code will have to look for ...

**Comment by BorzdeG** [comment]
Removed an unused method
