### ISSUE TITLE
Intellij crashes when i open more than two windows

### ISSUE THREAD

**Issue by bbary** [JetBrains/idea-gitignore#607]
Hello, 

this is the error i get when running more than one or two windows, i increases memory but still get this error

2019-09-26 15:38:35,196 [13139985]  ERROR - ecution.process.ProcessHandler - null 
java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor59.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.execution.process.ProcessHandler$5.invoke(ProcessHandler.java:223)
	at com.sun.proxy.$Proxy17.onTextAvailable(Unknown Source)
	at com.intellij.execution.process.ProcessHandler.notifyTextAvailable(ProcessHandler.java:197)
	at com.intellij.execution.process.BaseOSProcessHandler$SimpleOutputReader.onTextAvailable(BaseOSProcessHandler.java:198)
	at com.intellij.util.io.BaseOutputReader.sendText(BaseOutputReader.java:202)
	at com.intellij.util.io.BaseOutputReader.processInput(BaseOutputReader.java:186)
	at com.intellij.util.io.BaseOutputReader.readAvailableNonBlocking(BaseOutputReader.java:105)
	at com.intellij.util.io.BaseDataReader.readAvailable(BaseDataReader.java:85)
	at com.intellij.util.io.BaseDataReader.doRun(BaseDataReader.java:163)
	at com.intellij.util.io.BaseDataReader$1$1.run(BaseDataReader.java:66)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:209)
	at com.intellij.util.io.BaseDataReader$1.run(BaseDataReader.java:63)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.jetbrains.plugins.scala.project.template.Downloader$DownloadProcessAdapter.onTextAvailable(Downloader.scala:28)
	... 20 more
2019-09-26 15:38:35,287 [13140076]  ERROR - ecution.process.ProcessHandler - null 
java.lang.reflect.InvocationTargetException

**Comment by dmitriysmirnovjb** [comment]
How is it related to the .ignore plugin?

The exception seems to be caused by the Scala plugin, please report to https://youtrack.jetbrains.com/issues/
