### ISSUE TITLE
java.lang.Throwable: Already disposed: URL='(disposed)' in IntelliJ IDEA 2019.3.2

### ISSUE THREAD

**Issue by petr-nehez** [JetBrains/idea-gitignore#616]
### Prerequisites

* [X] Plugin is in the latest version
* [ ] Issue was not reported yet
* [X] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

Just after start...

```
java.lang.Throwable: Already disposed: URL='(disposed)'
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.intellij.openapi.vfs.impl.VirtualFilePointerImpl.checkDisposed(VirtualFilePointerImpl.java:91)
	at com.intellij.openapi.vfs.impl.VirtualFilePointerImpl.getFile(VirtualFilePointerImpl.java:59)
	at com.intellij.openapi.vfs.impl.VirtualFilePointerContainerImpl.cacheThings(VirtualFilePointerContainerImpl.java:223)
	at com.intellij.openapi.vfs.impl.VirtualFilePointerContainerImpl.getOrCache(VirtualFilePointerContainerImpl.java:205)
	at com.intellij.openapi.vfs.impl.VirtualFilePointerContainerImpl.getFiles(VirtualFilePointerContainerImpl.java:294)
	at com.intellij.openapi.roots.impl.libraries.LibraryImpl.getFiles(LibraryImpl.java:176)
	at com.intellij.openapi.roots.impl.LibraryOrderEntryBaseImpl.getRootFiles(LibraryOrderEntryBaseImpl.java:51)
	at com.intellij.openapi.roots.impl.ModuleLibraryOrderEntryImpl.getRootFiles(ModuleLibraryOrderEntryImpl.java:44)
	at com.intellij.util.indexing.FileBasedIndexScanRunnableCollectorImpl.lambda$collectScanRootRunnables$5(FileBasedIndexScanRunnableCollectorImpl.java:92)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:821)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:69)
	at com.intellij.util.indexing.FileBasedIndexScanRunnableCollectorImpl.collectScanRootRunnables(FileBasedIndexScanRunnableCollectorImpl.java:36)
	at com.intellij.util.indexing.FileBasedIndexImpl.collectScanRootRunnables(FileBasedIndexImpl.java:2398)
	at com.intellij.util.indexing.FileBasedIndexImpl.iterateIndexableFiles(FileBasedIndexImpl.java:2390)
	at com.intellij.util.indexing.FileBasedIndexImpl.projectIndexableFiles(FileBasedIndexImpl.java:1092)
	at com.intellij.util.indexing.FileBasedIndexImpl.processValuesInScope(FileBasedIndexImpl.java:953)
	at com.intellij.util.indexing.FileBasedIndexImpl.getValues(FileBasedIndexImpl.java:818)
	at mobi.hsz.idea.gitignore.indexing.IgnoreFilesIndex.getEntries(IgnoreFilesIndex.java:223)
	at mobi.hsz.idea.gitignore.IgnoreManager.lambda$new$0(IgnoreManager.java:285)
	at mobi.hsz.idea.gitignore.util.CachedConcurrentMap.get(CachedConcurrentMap.java:76)
	at mobi.hsz.idea.gitignore.IgnoreManager.isFileIgnored(IgnoreManager.java:336)
	at mobi.hsz.idea.gitignore.projectView.HideIgnoredFilesTreeStructureProvider.lambda$modify$0(HideIgnoredFilesTreeStructureProvider.java:90)
	at com.intellij.util.containers.ContainerUtil.findAll(ContainerUtil.java:1176)
	at com.intellij.util.containers.ContainerUtil.filter(ContainerUtil.java:1155)
	at mobi.hsz.idea.gitignore.projectView.HideIgnoredFilesTreeStructureProvider.modify(HideIgnoredFilesTreeStructureProvider.java:86)
	at com.intellij.ide.util.treeView.AbstractTreeStructureBase.getChildElements(AbstractTreeStructureBase.java:44)
	at com.intellij.ui.tree.StructureTreeModel.getValidChildren(StructureTreeModel.java:382)
	at com.intellij.ui.tree.StructureTreeModel.validateChildren(StructureTreeModel.java:300)
	at com.intellij.ui.tree.StructureTreeModel.getNode(StructureTreeModel.java:294)
	at com.intellij.ui.tree.StructureTreeModel.getChildren(StructureTreeModel.java:314)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.getNode(AsyncTreeModel.java:586)
	at com.intellij.ui.tree.AsyncTreeModel$ObsolescentCommand.get(AsyncTreeModel.java:481)
	at com.intellij.ui.tree.AsyncTreeModel$ObsolescentCommand.get(AsyncTreeModel.java:447)
	at com.intellij.util.concurrency.Command$Processor.lambda$process$1(Command.java:48)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:997)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:73)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:127)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:150)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:116)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:73)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:191)
	at com.intellij.util.concurrency.Invoker.lambda$offerSafely$0(Invoker.java:158)
	at com.intellij.util.concurrency.Invoker$Background.lambda$offer$0(Invoker.java:473)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:222)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:30)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:201)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:190)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### Steps to Reproduce

Unable to reproduce...

### Versions

**Plugin:** 3.2.3.193

**IDE:** 2019.3.2

**OS:** `RHEL 8.1`

### Additional information

It did happen also in other plugin - https://github.com/zielu/GitToolBox/issues/197.

**Comment by hsz** [comment]
Fixed with `v4.0.0`.
