### ISSUE TITLE
Incompatible with IDEA 2020.1 EAP

### ISSUE THREAD

**Issue by Thunderforge** [JetBrains/idea-gitignore#617]
### Description

The latest version of .ignore is reported as incompatible with Intellij IDEA 2020.1 EAP.

![image](https://user-images.githubusercontent.com/6200170/73078126-2de96900-3e87-11ea-9fdf-41dfbe2dfe2c.png)

### Versions

**Plugin:** 

```
3.2.3
```

**IDE:** 

```
IntelliJ IDEA 2020.1 EAP (Ultimate Edition)
Build #IU-201.3803.71
```

**OS:** 

```
Windows 10 1909
```

**Comment by shabtaisharon** [comment]
Join the request please 😃

**Comment by Thunderforge** [comment]
> Join the request please 😃

I don't understand what you mean by that.

**Comment by shabtaisharon** [comment]
That i would like to that fixed to and i join your request for a fix.

**Comment by RadianceL** [comment]
me too

**Comment by Scott-G** [comment]
Since the last few EAPs the below is thrown at start-up and plugin is automatically disabled. I am not seeing the incompatibility message as I cannot start with it enabled. 

`Plugin 'mobi.hsz.idea.gitignore' failed to initialize and will be disabled.  Please restart PhpStorm.

java.lang.NoClassDefFoundError: Could not initialize class mobi.hsz.idea.gitignore.IgnoreBundle
at mobi.hsz.idea.gitignore.file.IgnoreFileTypeFactory.createFileTypes(IgnoreFileTypeFactory.java:50)
at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.lambda$initStandardFileTypes$3(FileTypeManagerImpl.java:358)
at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processWithPluginDescriptor(ExtensionPointImpl.java:281)
at com.intellij.openapi.extensions.ExtensionPointName.processWithPluginDescriptor(ExtensionPointName.java:155)
at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.initStandardFileTypes(FileTypeManagerImpl.java:356)
at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.<init>(FileTypeManagerImpl.java:221)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
    at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:48)
    at com.intellij.serviceContainer.PlatformComponentManagerImpl.instantiateClassWithConstructorInjection(PlatformComponentManagerImpl.kt:567)
    at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:55)
    at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:41)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:113)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:69)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:62)
    at com.intellij.serviceContainer.PlatformComponentManagerImpl$preloadServices$future$1.run(PlatformComponentManagerImpl.kt:708)
    at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
    at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:223)
    at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:30)
    at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:202)
    at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:194)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)`

PhpStorm 2020.1 EAP
Build #PS-201.5259.18, built on February 13, 2020
PhpStorm EAP User
Expiration date: March 14, 2020
Runtime version: 11.0.6+8-b722.2 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: run.processes.with.pty=TRUE, debugger.watches.in.variables=false
Non-Bundled Plugins: Dummy Text Generator, zielu.gittoolbox, String Manipulation, com.darkyen.darkyenustimetracker, com.kstenschke.copypastestack, de.netnexus.camelcaseplugin, com.atlassian.bitbucket.references, net.seesharpsoft.intellij.plugins.csv, net.vektah.codeglance, nl.jworks.intellij.bootstrap3, com.intellij.plugins.html.instantEditing

**Comment by RalphBergmannKMB** [comment]
@shabtaisharon @RadianceL 

> Join the request please 😃
If you want to get notified about changes, just click the subscribe button on the right side ;-)

**Comment by jwiede** [comment]
Yep, definitely need this for 2020.1EAP and beyond.

**Comment by jwiede** [comment]
So is there any chance this will be fixed before the main IDEs EAP periods for 2020.1 end?  Is doing so even on anyone's radar?  If not, is external contribution welcome, and if so, what's the process?

**Comment by LouisCAD** [comment]
@dmitry-zhuravlev Is there any blocker for this issue? Can we help?

**Comment by dmitry-zhuravlev** [comment]
Compatibility changes will be available soon in 2020.1 release. Please stay tuned and sorry for inconvenience if any.

**Comment by tan9** [comment]
It [looks like](https://confluence.jetbrains.com/display/IDEADEV/IDEA+2020.1+latest+builds) that IntelliJ IDEA 2020.1 will be released very soon.

@dmitry-zhuravlev I knew that Russia is at a difficult time againsting coronavirus, hope everything goes well in your country.
@dmitriysmirnovjb @hsz would you please help fix this issue for the upcoming 2020.1 release?

**Comment by ruurd** [comment]
WebStorm 2020.1 has been released. Same problem with that.

**Comment by dmitriysmirnovjb** [comment]
Compatible version is available in the plugin repository an at tag/v3.2.3.201

**Comment by ruurd** [comment]
\o/ \o/ - that's fast! Thank you.

**Comment by Vinccool96** [comment]
Not published. WebStorm doesn't see the update so it's impossible to update the plugin.
