### ISSUE TITLE
Inspection run can't finish because of IgnoreUnusedEntryInspection

### ISSUE THREAD

**Issue by MaXal** [JetBrains/idea-gitignore#805]
Screenshots from profiler:
<img width="1320" alt="image" src="https://user-images.githubusercontent.com/266747/208965461-2bb86399-91e9-4bae-a11b-506f910b4b7c.png">

<img width="1334" alt="image" src="https://user-images.githubusercontent.com/266747/208965751-dd34bfd4-19a1-4ea3-aacc-e16aaeecc2c3.png">

Async snapshot:
[PS-231.SNAPSHOT-maxim.kolmakov--inspections-jfr-19700101010000.jfr.zip](https://github.com/JetBrains/idea-gitignore/files/10280014/PS-231.SNAPSHOT-maxim.kolmakov--inspections-jfr-19700101010000.jfr.zip)

The project is nothing unusual. Please, contact me if you need it for reproducing @maxim.kolmakov in Slack.

**Comment by MaXal** [comment]
The issue is still there. There is a freeze:
```
"JobScheduler FJ pool 3/11" #385 daemon prio=4 os_prio=0 cpu=1396878.32ms elapsed=1498.60s tid=0x00007f0b480647e0 nid=0x2c3e0 runnable  [0x00007f09c2515000]
   java.lang.Thread.State: RUNNABLE
	at com.intellij.openapi.progress.ProgressManager.checkCanceled(ProgressManager.java:229)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:291)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:328)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:328)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:328)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:328)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:328)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.processContentFilesRecursively(WorkspaceFileIndexImpl.kt:142)
	at com.intellij.openapi.roots.impl.FileIndexBase.iterateContentUnderDirectory(FileIndexBase.java:48)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.iterateContentUnderDirectory(ProjectFileIndexImpl.java:35)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.iterateContent(ProjectFileIndexImpl.java:50)
	at com.intellij.openapi.roots.impl.FileIndexBase.iterateContent(FileIndexBase.java:39)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.iterateContent(ProjectFileIndexImpl.java:35)
	at mobi.hsz.idea.gitignore.util.MatcherUtil$Companion.getFilesForPattern(MatcherUtil.kt:85)
	at mobi.hsz.idea.gitignore.reference.IgnoreReferenceSet$IgnoreReference.innerResolveInContext(IgnoreReferenceSet.kt:121)
	at com.intellij.psi.impl.source.resolve.reference.impl.providers.FileReference.innerResolveInContext(FileReference.java:188)
	at mobi.hsz.idea.gitignore.reference.IgnoreReferenceSet$IgnoreReference.innerResolveInContext(IgnoreReferenceSet.kt:103)
	at com.intellij.psi.impl.source.resolve.reference.impl.providers.FileReference.innerResolveInContext(FileReference.java:188)
	at mobi.hsz.idea.gitignore.reference.IgnoreReferenceSet$IgnoreReference.innerResolveInContext(IgnoreReferenceSet.kt:103)
	at com.intellij.psi.impl.source.resolve.reference.impl.providers.FileReference.innerResolve(FileReference.java:136)
	at com.intellij.psi.impl.source.resolve.reference.impl.providers.FileReference$MyResolver.resolve(FileReference.java:606)
	at com.intellij.psi.impl.source.resolve.reference.impl.providers.FileReference$MyResolver.resolve(FileReference.java:601)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$2(ResolveCache.java:176)
	at com.intellij.psi.impl.source.resolve.ResolveCache$$Lambda$3986/0x0000000801d8dc30.compute(Unknown Source)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:237)
	at com.intellij.psi.impl.source.resolve.ResolveCache$$Lambda$3988/0x0000000801d8e900.compute(Unknown Source)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:215)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:176)
	at com.intellij.psi.impl.source.resolve.reference.impl.providers.FileReference.multiResolve(FileReference.java:120)
	at mobi.hsz.idea.gitignore.codeInspection.IgnoreUnusedEntryInspection$buildVisitor$1.visitEntry(IgnoreUnusedEntryInspection.kt:49)
	at mobi.hsz.idea.gitignore.psi.IgnoreVisitor.visitEntryFile(IgnoreVisitor.java:19)
	at mobi.hsz.idea.gitignore.psi.impl.IgnoreEntryFileImpl.accept(IgnoreEntryFileImpl.java:21)
	at mobi.hsz.idea.gitignore.psi.impl.IgnoreEntryFileImpl.accept(IgnoreEntryFileImpl.java:26)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:82)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:57)
	at com.intellij.codeInspection.InspectionEngine.lambda$inspectElements$8(InspectionEngine.java:283)
	at com.intellij.codeInspection.InspectionEngine$$Lambda$4961/0x000000080229f598.process(Unknown Source)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.concurrency.ApplierCompleter$$Lambda$4963/0x000000080229fa38.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1133)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
	at com.intellij.concurrency.ApplierCompleter$$Lambda$3746/0x0000000801c12c68.run(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager$$Lambda$1244/0x0000000800d59e88.compute(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:86)
	at java.util.concurrent.CountedCompleter.exec(java.base@17.0.6/CountedCompleter.java:754)
	at java.util.concurrent.ForkJoinTask.doExec(java.base@17.0.6/ForkJoinTask.java:373)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(java.base@17.0.6/ForkJoinPool.java:1182)
	at java.util.concurrent.ForkJoinPool.scan(java.base@17.0.6/ForkJoinPool.java:1655)
	at java.util.concurrent.ForkJoinPool.runWorker(java.base@17.0.6/ForkJoinPool.java:1622)
	at java.util.concurrent.ForkJoinWorkerThread.run(java.base@17.0.6/ForkJoinWorkerThread.java:165)
```

**Comment by hsz** [comment]
ac9bdf51d10dca475d90245aede9d820f54759ca
