### ISSUE TITLE
Exception: missing implementation of abstract method (IntelliJ 2023.1 EAP)

### ISSUE THREAD

**Issue by james-interfold** [JetBrains/idea-gitignore#809]
### Prerequisites

* [X] Plugin is in the latest version
* [X] Issue was not reported yet
* [X] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

```
CloseIgnoredEditorsAction#update@MainMenu (mobi.hsz.idea.gitignore.actions.CloseIgnoredEditorsAction), actionId=CloseIgnoredEditors, text='Close Ignored'

java.lang.AbstractMethodError: Missing implementation of resolved method 'abstract boolean isFileToClose(com.intellij.openapi.fileEditor.impl.EditorComposite, com.intellij.openapi.fileEditor.impl.EditorWindow, com.intellij.openapi.fileEditor.ex.FileEditorManagerEx)' of abstract class com.intellij.ide.actions.CloseEditorsActionBase.
	at com.intellij.ide.actions.CloseEditorsActionBase.getFilesToClose(CloseEditorsActionBase.java:33)
	at com.intellij.ide.actions.CloseEditorsActionBase.isActionEnabled(CloseEditorsActionBase.java:88)
	at mobi.hsz.idea.gitignore.actions.CloseIgnoredEditorsAction.isActionEnabled(CloseIgnoredEditorsAction.kt:30)
	at com.intellij.ide.actions.CloseEditorsActionBase.update(CloseEditorsActionBase.java:73)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performDumbAwareUpdate$0(ActionUtil.java:158)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:181)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doUpdate(ActionUpdater.java:720)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$updateActionReal$4(ActionUpdater.java:136)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$computeOnEdt$7(ActionUpdater.java:233)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$1(ProgressManager.java:70)
```

### Steps to Reproduce

1. Start the IDE with .ignore installed and enabled.
2. Load a project.
3. Open **Search Everywhere**.

**Reproduces how often:** 

This has only happened once.

### Versions

**Plugin:** 
```
4.4.4
```

**IDE:** 

```
IntelliJ IDEA 2023.1 EAP (Ultimate Edition)
Build #IU-231.4840.387, built on January 19, 2023
Licensed to IntelliJ IDEA EAP user: ...
Expiration date: February 18, 2023
Runtime version: 17.0.5+8-b759.1 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.1
GC: Shenandoah Pauses, Shenandoah Cycles
Memory: 4096M
Cores: 8
Metal Rendering is ON
Registry:
    ide.mac.alt.mnemonic.without.ctrl=false
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.github.leomillon.uuidgenerator (4.5.1)
    org.jetbrains.plugins.go (231.4840.387)
    org.jetbrains.idea.grammar (2022.3)
    AceJump (3.8.10)
    de.netnexus.camelcaseplugin (3.0.12)
    ski.chrzanow.foldableprojectview (1.1.4)
    org.intellij.prisma (231.4840.362)
    Pythonid (231.4840.387)

Kotlin: 231-1.7.21-release-272-IJ4840.387
```

**OS:** 

```
  System Version:	macOS 13.1 (22C65)
  Model Identifier:	MacBookPro18,3
  Model Number:	MKGP3LL/A
  Chip:	Apple M1 Pro
  Memory:	16 GB
```

**Comment by hsz** [comment]
Thanks, fixed with ce1676026ab584af12ded7782db754691f84f959
