### ISSUE TITLE
Severe error stacktrace on startup using WSL2 - ActionGroup

### ISSUE THREAD

**Issue by benfreke** [JetBrains/idea-gitignore#829]
### Prerequisites

* [X] Plugin is in the latest version
* [X] Issue was not reported yet
* [X] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

There is an error when running PhpStorm via WSL2. It shows in the logs output by the "Ubunu window". But I'm not seeing any issues in the UI of PhpStorm.

I'm logging it here so it is known about.

```
2023-05-09 11:14:07,882 [  28733] SEVERE - #c.i.o.a.i.ActionUpdater - UnignoreFileGroupAction#getChildren@EditorPopup(preload-bgt) (mobi.hsz.idea.gitignore.actions.UnignoreFileGroupAction), actionId=Ignore.UnignoreGroup, text='Add to ignore file (unignore)'                                                                                                         java.util.ConcurrentModificationException                                                                                                                                                    at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:756)                                                                                             at java.base/java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:788)                                                                                                at java.base/java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:786)                                                                                                at mobi.hsz.idea.gitignore.actions.IgnoreFileGroupAction.getChildren(IgnoreFileGroupAction.kt:169)                                                                                   at com.intellij.openapi.actionSystem.impl.ActionUpdater.doGetChildren(ActionUpdater.java:728)                                                                                        at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$new$1(ActionUpdater.java:128)                                                                                         at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$callAction$5(ActionUpdater.java:189)                                                                                  at com.intellij.diagnostic.telemetry.TraceKt.computeWithSpan(trace.kt:123)                                                                                                           at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.java:185)                                                                                           at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.java:164)                                                                                           at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$new$2(ActionUpdater.java:128)                                                                                         at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$getGroupChildren$23(ActionUpdater.java:528)                                                                           at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)                                                                                     at com.intellij.openapi.actionSystem.impl.ActionUpdater.getGroupChildren(ActionUpdater.java:536)                                                                                     at com.intellij.openapi.actionSystem.impl.ActionUpdater.doExpandActionGroup(ActionUpdater.java:520)                                                                                  at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild(ActionUpdater.java:604)                                                                                     at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroup$22(ActionUpdater.java:521)                                                                        at com.intellij.util.containers.ContainerUtil.concat(ContainerUtil.java:1538)                                                                                                        at com.intellij.openapi.actionSystem.impl.ActionUpdater.doExpandActionGroup(ActionUpdater.java:521)                                                                                  at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandActionGroup(ActionUpdater.java:309)                                                                                    at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroupAsync$14(ActionUpdater.java:372)                                                                   at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroupAsync$15(ActionUpdater.java:392)                                                                   at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1102)                                                                                 at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$tryRunReadActionAndCancelBeforeWrite$19(ActionUpdater.java:424)                                                       at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)                                               at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:129)                                                          at com.intellij.openapi.actionSystem.impl.ActionUpdater.tryRunReadActionAndCancelBeforeWrite(ActionUpdater.java:420)                                                                 at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroupAsync$16(ActionUpdater.java:392)                                                                   at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)                                                                          at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)                                                        at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)                                                                      at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)                                                                         at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)                                                                  at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)                                                                   at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)                                                                                   at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:361)                                                                  at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroupAsync$17(ActionUpdater.java:391)                                                                   at io.opentelemetry.context.Context.lambda$wrap$1(Context.java:212)                                                                                                                  at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:248)                                                                                             at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:28)                                                                                         at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:221)                                                                    at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:227)                                                                                                    at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:210)                                                                                             at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)                                                                                         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)                                                                                         at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)                                                                                      at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)                                                                                      at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)                                                                                                  at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)                                                                                        at java.base/java.lang.Thread.run(Thread.java:833)                                                                                                                           2023-05-09 11:14:07,884 [  28735] SEVERE - #c.i.o.a.i.ActionUpdater - PhpStorm 2023.1.1  Build #PS-231.8770.68                                                                       2023-05-09 11:14:07,884 [  28735] SEVERE - #c.i.o.a.i.ActionUpdater - JDK: 17.0.6; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.                                            2023-05-09 11:14:07,885 [  28736] SEVERE - #c.i.o.a.i.ActionUpdater - OS: Linux                                                                                                      2023-05-09 11:14:07,885 [  28736] SEVERE - #c.i.o.a.i.ActionUpdater - Plugin to blame: .ignore version: 4.5.0                                                                        2023-05-09 11:14:08,181 [  29032]   WARN - #c.i.o.a.ActionStub - ActionGroup should be registered using <group> tag: id="Ignore.New" class="mobi.hsz.idea.gitignore.actions.NewFileGroupAction" 
```

### Steps to Reproduce

1. Start PhpStorm in WSL2
2. Watch the logs and see the "severe" error show up. 
3. PhpStorm continues to operate as expected

**Expected behavior:**

No stacktrace errors to be in the logs.

**Actual behavior:** 

Stacktrace error as above, along with a warning about that is probably related.

```
2023-05-09 11:14:08,181 [  29032]   WARN - #c.i.o.a.ActionStub - ActionGroup should be registered using <group> tag: id="Ignore.New" class="mobi.hsz.idea.gitignore.actions.NewFileGroupAction"
```

**Reproduces how often:** 

100% of the time

### Versions

**Plugin:** 

```
4.5.0
```

**IDE:** 

```
PhpStorm 2023.1.1
Build #PS-231.8770.68, built on April 29, 2023
Licensed to ########
Subscription is active until March 8, 2024.
Runtime version: 17.0.6+10-b829.9 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.15.90.1-microsoft-standard-wsl2
GC: G1 Young Generation, G1 Old Generation
Memory: 958M
Cores: 12
Registry:
    debugger.new.tool.window.layout=true
    run.processes.with.pty=TRUE
    ide.experimental.ui=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    com.github.lppedd.idea-conventional-commit (0.22.0)
    com.github.copilot (1.2.5.2507)
    ru.adelf.idea.dotenv (2023.1)
    de.espend.idea.php.toolbox (6.2.0)
    de.espend.idea.php.annotation (9.2.1)
    uk.co.ben-gibson.remote.repository.mapper (4.3.2)
    zielu.gittoolbox (500.0.6+213)
    mobi.hsz.idea.gitignore (4.5.0)

Current Desktop: Undefined
```

**OS:** 

```
Windows 10
PhpStorm running in WSL2, Ubuntu.
```

### Additional Information

There may be some new UI related issues, as I'm using that as well.

**Comment by hsz** [comment]
Thank you for reporting, fixed.
